[tool.poetry]
name = "ultimate-pollbot"
version = "1.0.0"
description = "A telegram bot for creating all kinds of polls."
authors = ["Arne Beer <contact@arne.beer>"]
license = "MIT"
repository = "https://github.com/nukesor/ultimate-poll-bot"

[tool.poetry.dependencies]
python = ">=3.8"
raven = "^6"
alembic = "^1"
telethon = "^1.11.0"
cryptg = "^0.2"
SQLAlchemy = "^1"
sqlalchemy-utils = "^0.36"
psycopg2-binary = "^2"
python-dateutil = "^2"
toml = "^0.10"
python-i18n = {version = "^0.3", extras = ["yaml"]}

matplotlib = "3.1"
pandas = "^0.24"
pillow = "^7.0"

[tool.poetry.dev-dependencies]
pytest-mock = "^1.10"
pytest = "^4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
